name: multiple-myeloma-classifier 
channels:
- conda-forge
dependencies:
- conda-forge::python=3.5
- conda-forge::pandas=0.22.0
- conda-forge::scikit-learn=0.19.1
- conda-forge::sklearn-contrib-lightning=0.5.0
- conda-forge::dask-searchcv=0.2.0
- conda-forge::numpy=1.14.3
- conda-forge::statsmodels=0.8.0
- conda-forge::matplotlib=2.2.2
- conda-forge::seaborn=0.8.1
- conda-forge::plotnine=0.3.0
- conda-forge::jupyter=1.0.0
- conda-forge::ipykernel=4.8.1
- conda-forge::r-irkernel=0.8.11
- conda-forge::widgetsnbextension=2.0.0
- conda-forge::nb_conda_kernels=2.1.0
- conda-forge::r-readr=1.1.1
- conda-forge::r-readxl=1.1.0
- conda-forge::r-ggplot2=2.2.1
- conda-forge::r-dplyr=0.7.4
- conda-forge::r-ggrepel=0.7.0
